name: Feature Request
description: Suggest a new feature or enhancement for Lemon API
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe the problem.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: The API could provide a new endpoint that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - Authentication
        - Authorization
        - API Endpoints
        - Security
        - Performance
        - Documentation
        - Testing
        - DevOps/CI
        - Other
    validations:
      required: false

  - type: checkboxes
    id: breaking
    attributes:
      label: Breaking Changes
      description: Would this feature require breaking changes?
      options:
        - label: This feature would require breaking changes to the API
          required: false
        - label: This feature maintains backward compatibility
          required: false

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this feature benefit users?
      placeholder: |
        - Improved security
        - Better developer experience
        - Reduced latency
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature
    validations:
      required: false
